config/routes.rb
Rails.application.routes.draw do
  root 'images#index'
  resources :images

  post 'images/create_comment'

  get 'user/:id' => 'users#show', as: 'show_user'

  ActiveAdmin.routes(self)
  devise_for :users

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized? (action, subject = nil)
    user.admin?
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :picture,
                    styles: {medium: '400x400>', thumb: '150x150>'},
                    default_url: '/image/:style/missing.png'
  validates_attachment_content_type :picture,
                                    presence: true,
                                    content_type: ['image/jpeg', 'image/png']

  validates :title, presence: true, length: {maximum: 50}

  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :grade, presence: true,
            numericality: { greater_than_or_equal_to: 1, maximum: 5 }
  validates :content, presence: true, length: {maximum: 180 }

  belongs_to :user
  belongs_to :image
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
          :validatable
  validates :name, presence: true, length: {maximum: 50}

  has_many :images
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def access_denied(exception)
    flash[:danger] = exception.message
    # redirect_to root_url
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :current_user, only: [:create, :destroy]
  def new
    @image = Image.new
  end

  def create
    @image = current_user.images.build(image_params)
    if @image.save
      flash[:success] = 'You have created new post!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @image = Image.destroy(params[:id])
    redirect_to root_url
  end

  def index
    # @images = Image.paginate(:page => params[:page], :per_page => 10)
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
    @message = Message.new
    @messages = Message.all.where(@message.image_id == @image.id)
    @messages.order(created_at: 'desc')
    @average_score = get_average_score
  end

  GRADES = [1, 2, 3, 4, 5]


  def create_comment
    if user_signed_in?
      @message = current_user.messages.build(message_params)
      @message.image_id = params[:id]
    end
    if @message.save
      flash[:success] = 'You have created new comment!'
      redirect_to root_url
    else
      render 'new'
    end
  end


  private

  def image_params
    params.require(:Image).permit(:picture, :title, :user_id)
  end

  def message_params
    params.require(:message).permit(:content, :grade, :user_id, :image_id)
  end

  def get_average_score
    average_score = 0
    @messages = Message.where(@message.image_id == params[:id])
    counter = 0
    @messages.each do |message|
      counter += 1
      average_score += message.grade
      average_score/= counter
    end
    return average_score.round(2)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in?
  before_action :current_user
  def show
    @user = User.find(params[:id])
    @images = Image.where(@user.id == params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_for @image, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @image.errors[:title].any? %>">
      <%= f.label :title, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @image, field_name: :title %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @image.errors[:picture].any? %>">
      <%= f.label :picture, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.file_field :picture, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @image, field_name: :picture %>
      </div>
    </div>



    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/images/index.html.erb
<div class="row">
<% @images.each do |image| %>

  <div class="col-md-3">
    <%= image_tag image.picture.url(:thumb) %></br>
    <b><%= link_to image.title, image_path(image) %></b></br>
    <p>By: <%= link_to image.user.name, show_user_path(image.user.id) %></p>
  </div>
<% end %>
</div>

app/views/images/new.html.erb
<h1>Create new photo</h1>
<%= render 'images/form' %>

app/views/images/show.html.erb
<h1><%= @image.title %></h1>

<%= image_tag @image.picture.url(:medium) %>

<p>Average score: <%= @average_score %> </p>

<% if user_signed_in? %>
    <h1>Add comment</h1>

    <%= form_for :message, url: images_create_comment_path do |f| %>
        <div class="form-group <%= 'has-error' if @message.errors[:content].any? %>">
          <%= f.label :content, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.text_field :content, class: 'form-control' %>
            <%= render 'shared/field_errors', object: @message, field_name: :content %>
          </div>
        </div>

        <div class="form-group <%= 'has-error' if @message.errors[:grade].any? %>">
          <%= f.label :grade, class: 'col-sm-2 control-label' %>
          <div class="col-sm-10">
            <%= f.select :grade, ImagesController::GRADES, {} %>
            <%= render 'shared/field_errors', object: @message, field_name: :grade %>
          </div>
        </div>


        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
    <% end %>
<% end %>

<h1>Comments</h1>
<% if @image.id == params[:id] %>
    <% @messages.each do |message| %>
        <div class="panel panel-default">
          <p>By: <%= message.user.name %>, score: <%= message.grade %></p>
          <%= message.content %>
        </div>
    <% end %>
<% else %>
    <p>No comments yet</p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Photo Gallery', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Pages links -->
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Logged in as <%= current_user.name %>
          </p>
          <ul class="nav navbar-nav">

                <% if current_user.admin? %>
                  <li><%= link_to 'Admin Panel', admin_root_path %></li>
                <% end %>
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>

          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageStudio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

<div class="container">

  <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>

  <%= yield %>

</div>

</body>
</html>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>' profile
</h1>
<%= link_to 'Edit profile', edit_user_registration_path(current_user)%>

<p>My photos <%= link_to 'Create new photo', new_image_path %></p>

<table class="table table-bordered">
  <tr>
    <th>Photo</th>
    <th>Title</th>
    <th>Action</th>
  </tr>
  <% @images.each do |image| %>
  <tr>
    <th><%= image_tag image.picture.url(:thumb) %></th>
    <th><%= image.title %></th>
    <th><%= link_to 'Remove', image_path, method: :delete %></th>
  </tr>
  <% end %>
</table>